# Generated by Django 3.1.3 on 2020-11-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('nok_address', models.CharField(max_length=100)),
                ('nok_phone', models.CharField(max_length=100)),
                ('mstatus', models.CharField(max_length=100)),
                ('passport', models.ImageField(upload_to='passports/')),
                ('sig', models.ImageField(upload_to='sigs/')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
    ]
